name: Release Dockit

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Run Build Script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Remove Quarantine
        run: |
          cd dist/dockit
          xattr -d com.apple.quarantine dockit || true
          xattr -d com.apple.quarantine . || true
          # Add a note about security
          echo "Note: If you get a security warning, run: xattr -d com.apple.quarantine dockit" > SECURITY_NOTE.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/dockit.zip
            dist/dockit/SECURITY_NOTE.txt
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}