name: dockit

services:
  nginx:
    hostname: dockit_nginx
    container_name: dockit_nginx
    image: nginx:latest
    ports:
      - "${APP_PORT:-7070}:80"
    volumes:
      - ./:/var/www/html
      - ./dockit/nginx-latest/laravel.conf:/etc/nginx/conf.d/default.conf
  node:
    hostname: dockit_node
    container_name: dockit_node
    image: node:lts-jod
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["/bin/bash", "-c", "npm i && node index.js"]
  php:
    hostname: dockit_php
    container_name: dockit_php
    image: dockit-php-8.4
    build:
      context: ./dockit/php-8.4
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./dockit/php-8.4/php.ini:/usr/local/etc/php/php.ini
      - ./dockit/php-8.4/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  postgres:
    hostname: dockit_postgres
    container_name: dockit_postgres
    image: postgres:latest
    volumes:
      - ./dockit/data/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-dockit}
