name: Version Bump

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Bump version
        run: |
          python scripts/bump_version.py ${{ github.event.inputs.bump_type || 'patch' }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          commit-message: 'Bump version'
          title: 'Version bump'
          body: |
            Automated version bump
            - Bump type: ${{ github.event.inputs.bump_type || 'patch' }}
          branch: version-bump
          base: main
          labels: |
            version-bump
            automated pr 